name: Snyk Security Scan

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  snyk-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Snyk
        run: npm install -g snyk

      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk Test
        run: snyk test --severity-threshold=high

      - name: Monitor Project
        run: snyk monitor